# Generated by Django 5.1.5 on 2025-01-30 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sorteo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sorteopremio",
            name="premio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sorteopremios",
                to="sorteo_app.premio",
            ),
        ),
        migrations.AlterField(
            model_name="sorteopremio",
            name="sorteo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sorteopremios",
                to="sorteo_app.sorteo",
            ),
        ),
    ]
